apiVersion: apps/v1
kind: Deployment
metadata:
  name: openpolicy-api
  labels:
    app: openpolicy-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openpolicy-api
  template:
    metadata:
      labels:
        app: openpolicy-api
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/openpolicy-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: openpolicy-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: openpolicy-secrets
                  key: SECRET_KEY
            - name: ALLOWED_ORIGINS
              value: "https://yourdomain.com"
            - name: ALLOWED_HOSTS
              value: "yourdomain.com"
          readinessProbe:
            httpGet:
              path: /api/v1/health/detailed
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"