apiVersion: apps/v1
kind: Deployment
metadata:
  name: openpolicy-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openpolicy-api
  template:
    metadata:
      labels:
        app: openpolicy-api
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/openpolicy-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: openpolicy-secrets
                  key: DATABASE_URL
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: openpolicy-secrets
                  key: SECRET_KEY
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20