apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | default .Chart.Name }}
spec:
  replicas: {{ .Values.replicas | default 2 }}
  selector:
    matchLabels:
      app: {{ .Values.name | default .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name | default .Chart.Name }}
    spec:
      containers:
        - name: {{ .Values.name | default .Chart.Name }}
          image: {{ .Values.image | default "nginx:alpine" | quote }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.port | default 8080 }}
          env:
            - name: PORT
              value: "{{ .Values.port | default 8080 }}"
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.port | default 8080 }}
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.port | default 8080 }}
            initialDelaySeconds: 5
            periodSeconds: 15
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"