apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name | default .Chart.Name }}
spec:
  selector:
    app: {{ .Values.name | default .Chart.Name }}
  ports:
    - name: http
      port: {{ .Values.port | default 8080 }}
      targetPort: {{ .Values.port | default 8080 }}