name: Services Matrix

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  matrix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip pyyaml
      - name: Generate service list
        id: svcs
        run: |
          python - << 'PY'
import yaml, json
inv=yaml.safe_load(open('docs/reference/services.inventory.yaml'))
svcs=[s['path'] for s in inv['services']]
print('::set-output name=list::'+json.dumps(svcs))
PY
      - name: Build (dry-run)
        run: |
          echo "Services: ${{ steps.svcs.outputs.list }}"