name: Smoke on Push/PR

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and run
        run: |
          cp env.example .env
          echo "SECRET_KEY=$(openssl rand -hex 32)" >> .env
          docker compose up -d --build postgres api web
          for i in {1..30}; do
            if curl -fsS http://localhost:8000/api/v1/health >/dev/null; then exit 0; fi
            sleep 2
          done
          echo "API not healthy" >&2
          docker ps
          exit 1

